### ISSUE TITLE
Exposed mongodb+srv credentials

### ISSUE THREAD

**Issue by eth0izzle** [GinaKui/contact-book#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@sandbox-7mgdy.mongodb.net` in file [/config/default.json](https://github.com/GinaKui/contact-book/blob/master/config/default.json)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by GinaKui** [comment]
the credential is recycled. Thanks!
